// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace InsertGuid
{
    internal sealed partial class Vsix
    {
        public const string Id = "InsertGuid.e3823a54-594f-449c-ac9f-16c9c8d4d89a";
        public const string Name = "Insert Guid";
        public const string Description = @"Insert a Guid into the text";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Osama AbuSitta";
        public const string Tags = "guid";
    }
}
